### ISSUE TITLE
菜单栏汉化 以及 单独提供汉化后的文件下载

### ISSUE THREAD

**Issue by Ryongyon** [gouzil/github-desktop-zh#12]
### The feature request

rt

### Proposed solution

rt

**Comment by gouzil** [comment]
菜单栏晚些会更新, 汉化后打包的文件在[Releases](https://github.com/gouzil/github-desktop-zh/releases)里

**Comment by Ryongyon** [comment]
@gouzil 

十分感谢作者抽出时间回复。
作者有没有考虑额外提供一个只含有 `main.js` `renderer.js` 这两个文件的压缩包呢？
对于本就已经安装了程序的人来说步骤有些多，为了提取这两个汉化文件还得下载100mb左右的文件，然后还得进去包找出来，再去覆盖。

**Comment by gouzil** [comment]
> @gouzil
> 
> 十分感谢作者抽出时间回复。 作者有没有考虑额外提供一个只含有 这两个文件的压缩包呢？ 对于本就已经安装了程序的人来说步骤有些多，为了提取这两个汉化文件还得下载100mb左右的文件，然后还得进去包找出来，再去覆盖。`main.js``renderer.js`

菜单栏汉化已经添加上了,  关于`main.js``renderer.js`这两个文件也已经上传, 但是很有可能会触发苹果的 sip (系统完整性保护) 校验不通过

**Comment by Ryongyon** [comment]
@gouzil 
十分感谢！
